src/Entity/Certificat.php
<?php

namespace App\Entity;

use App\Repository\CertificatRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CertificatRepository::class)
 */
class Certificat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $avis_traitant;

    // /**
    //  * @ORM\Column(type="text", nullable=true)
    //  */
    // private $decision;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $plainte_doleance;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $examen_clinique;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $avis_medecin_conseil;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $examens_complementaires;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $expertise_demandee;

    /**
     * @ORM\ManyToOne(targetEntity=Specialite::class, inversedBy="certificats")
     */
    private $specialite;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $medecin;

    /**
     * @ORM\ManyToOne(targetEntity=Pathologie::class, inversedBy="certificats")
     */
    private $pathologie;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="certificats")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAvisTraitant(): ?string
    {
        return $this->avis_traitant;
    }

    public function setAvisTraitant(?string $avis_traitant): self
    {
        $this->avis_traitant = $avis_traitant;

        return $this;
    }

    // public function getDecision(): ?string
    // {
    //     return $this->decision;
    // }

    // public function setDecision(?string $decision): self
    // {
    //     $this->decision = $decision;

    //     return $this;
    // }

    public function getPlainteDoleance(): ?string
    {
        return $this->plainte_doleance;
    }

    public function setPlainteDoleance(?string $plainte_doleance): self
    {
        $this->plainte_doleance = $plainte_doleance;

        return $this;
    }

    public function getExamenClinique(): ?string
    {
        return $this->examen_clinique;
    }

    public function setExamenClinique(?string $examen_clinique): self
    {
        $this->examen_clinique = $examen_clinique;

        return $this;
    }

    public function getAvisMedecinConseil(): ?string
    {
        return $this->avis_medecin_conseil;
    }

    public function setAvisMedecinConseil(?string $avis_medecin_conseil): self
    {
        $this->avis_medecin_conseil = $avis_medecin_conseil;

        return $this;
    }

    public function getExamensComplementaires(): ?string
    {
        return $this->examens_complementaires;
    }

    public function setExamensComplementaires(?string $examens_complementaires): self
    {
        $this->examens_complementaires = $examens_complementaires;

        return $this;
    }

    public function getExpertiseDemandee(): ?string
    {
        return $this->expertise_demandee;
    }

    public function setExpertiseDemandee(?string $expertise_demandee): self
    {
        $this->expertise_demandee = $expertise_demandee;

        return $this;
    }

    public function getSpecialite(): ?Specialite
    {
        return $this->specialite;
    }

    public function setSpecialite(?Specialite $specialite): self
    {
        $this->specialite = $specialite;

        return $this;
    }

    public function getMedecin(): ?string
    {
        return $this->medecin;
    }

    public function setMedecin(?string $medecin): self
    {
        $this->medecin = $medecin;

        return $this;
    }

    public function hasExpertise(){
        return $this->specialite ? true : false;
    }

    public function isAvailable(){
        return $this->specialite && $this->expertise_demandee ? true : false;
    }

    public function goToSpecialist(){
        return $this->specialite ? true : false;
    }

    public function hasMedecin(){
        return $this->medecin ? true : false;
    }

    public function isComplet(){
        return $this->expertise_demandee && $this->examens_complementaires;
    }

    public function getPathologie(): ?Pathologie
    {
        return $this->pathologie;
    }

    public function setPathologie(?Pathologie $pathologie): self
    {
        $this->pathologie = $pathologie;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    
}

src/Form/CertificatType.php
<?php

namespace App\Form;

use App\Entity\Certificat;
use App\Entity\Pathologie;
use App\Entity\Specialite;
use App\Repository\SpecialiteRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CertificatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('avis_traitant')
            ->add('pathologie', EntityType::class, [
                'class' => Pathologie::class,
                'choice_label' => 'nom',
                'placeholder' => 'Veuillez choisir une pathologie',
                'required' => false
            ])
            ->add('plainte_doleance', null, [
                'label' => 'Plainte / Doléance'
            ])
            ->add('examen_clinique')
            ->add('avis_medecin_conseil')
            ->add('examen', ChoiceType::class, [
                'mapped' => false,
                'choices'  => [
                    'OUI' => '1',
                    'NON' => '0',
                ],
                'label' => 'Examens complémentaires Demandes',
                'expanded' => true,
                'required' => false,
            ])
            ->add('expertise', ChoiceType::class, [
                'mapped' => false,
                'choices'  => [
                    'OUI' => '1',
                    'NON' => '0',
                ],
                'label' => 'Expertise demandée',
                'expanded' => true,
                'required' => false,
                
            ])
            ->add('examens_complementaires')
            ->add('expertise_demandee')
            ->add('medecin')
            ->add('specialite', EntityType::class, [
                'class' => Specialite::class,
                'choice_label' => 'nom',
                'placeholder' => 'Veuillez choisir une spécialité',
                'required' => false,
                'query_builder' => function(SpecialiteRepository $specialiteRepository){
                    return $specialiteRepository->createQueryBuilder('s')->orderBy('s.nom', 'ASC');
                }
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Certificat::class,
        ]);
    }
}

src/Controller/CertificatController.php
<?php

namespace App\Controller;

use App\Entity\Patient;
use App\Entity\Certificat;
use App\Form\CertificatType;
use App\Entity\Questionnaire;
use App\Service\QuestionnaireService;
use App\Repository\CertificatRepository;
use App\Repository\QuestionnaireRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/certificat")
 */
class CertificatController extends AbstractController
{
    public $qs;
    public $qR;
    public function __construct(QuestionnaireService $qs, QuestionnaireRepository $qR)
    {
        $this->qs = $qs;
        $this->qR = $qR;
    }
    /**
     * @Route("/", name="app_certificat_index", methods={"GET"})
     */
    public function index(CertificatRepository $certificatRepository): Response
    {
        return $this->render('certificat/index.html.twig', [
            'certificats' => $certificatRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_certificat_new", methods={"GET", "POST"})
     */
    public function new(Request $request, CertificatRepository $certificatRepository): Response
    {
        $certificat = new Certificat();
        $form = $this->createForm(CertificatType::class, $certificat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $certificat->setUser($this->getUser());
            $certificatRepository->add($certificat, true);

            return $this->redirectToRoute('coneil_patient', ['id'=>$this->qs->questionnaireByCertificat($certificat->getId())->getConseil()->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('certificat/new.html.twig', [
            'certificat' => $certificat,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_certificat_show", methods={"GET"})
     */
    public function show(Certificat $certificat): Response
    {
        return $this->render('certificat/show.html.twig', [
            'certificat' => $certificat,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_certificat_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Certificat $certificat, CertificatRepository $certificatRepository): Response
    {
        $form = $this->createForm(CertificatType::class, $certificat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $certificat->setUser($this->getUser());
            $certificatRepository->add($certificat, true);
            
            return $this->redirectToRoute('coneil_patient', ['id'=>$this->qs->questionnaireByCertificat($certificat->getId())->getConseil()->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('certificat/edit.html.twig', [
            'certificat' => $certificat,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_certificat_delete", methods={"POST"})
     */
    public function delete(Request $request, Certificat $certificat, CertificatRepository $certificatRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$certificat->getId(), $request->request->get('_token'))) {
            $certificatRepository->remove($certificat, true);
        }

        return $this->redirectToRoute('app_certificat_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/delete/{id}", name="app_delete_certificat", methods={"GET"})
     */
    public function deleteCertificat(Request $request, Certificat $certificat, CertificatRepository $certificatRepository): Response
    {
       // dd($certificat);
        if ($certificat) {
            $questionnaire = $this->qs->questionnaireByCertificat($certificat->getId());
            $questionnaire->setCertificat(new Certificat());
            $this->qR->add($questionnaire);
            $certificatRepository->remove($certificat, true);
            return $this->redirectToRoute('coneil_patient', ['id'=>$this->qs->questionnaireByCertificat($certificat->getId())->getConseil()->getId()], Response::HTTP_SEE_OTHER);
        }
    }

    /**
     * @Route("/new/{id}", name="app_certificat_new_patient")
     */
    public function newWithPathient(Questionnaire $questionnaire, Request $request, CertificatRepository $certificatRepository, QuestionnaireRepository $questionnaireRepository): Response
    {
        $certificat = new Certificat();
        $form = $this->createForm(CertificatType::class, $certificat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $certificatRepository->add($certificat, true);
            //$questionnaire = $patient->getQuestionnaires()->last();
            $questionnaire->setCertificat($certificat);
            $questionnaireRepository->add($questionnaire, true);
            return $this->redirectToRoute('coneil_patient', ['id'=>$questionnaire->getConseil()->getId()], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('certificat/new.html.twig', [
            'certificat' => $certificat,
            'questionnaire' => $questionnaire,
            'form' => $form,
        ]);
    }
}

templates/certificat/_delete_form.html.twig
<form method="post" action="{{ path('app_certificat_delete', {'id': certificat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ certificat.id) }}">
    <button class="btn btn-btndelete">Delete</button>
</form>

templates/certificat/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.avis_traitant) }}
    {{ form_row(form.plainte_doleance) }}
    {{ form_row(form.examen_clinique) }}
    {{ form_row(form.avis_medecin_conseil) }}{{ form_row(form.examen) }}
    <div class="row" id="examen">
        {{ form_row(form.examens_complementaires)}}
    </div>
    {{ form_row(form.expertise) }}
    <div class="row" id="expertise">
        {{ form_row(form.expertise_demandee)}}
    </div>
    
    {{ form_rest(form) }}
    <button class="btn btn-{{btn_c}}">{{ button_label|default('Save') }}</button>
    {% if app.request.attributes.get('_route') == 'app_certificat_edit' %}
        {# <a href="{{ path('app_delete_certificat', {'id': certificat.id}) }}" class="btn btn-btndelete" onclick="return confirm('Etes-vous sûr de vouloir supprimer cet élément?');">{{ 'btnSupprimer'|trans }}</a> #}
    {% endif %}
    {% if app.request.attributes.get('_route') == 'app_certificat_edit' %}
        <a href="{{ path('coneil_patient', {'id': getQuestionnaireByCertificat(certificat.id).conseil.id}) }}" class="btn btn-btnback">{{ 'btnRetour' | trans}}</a>
    {% endif %}

    {% if app.request.attributes.get('_route') == 'app_certificat_new_patient' %}
            <a href="{{ path('coneil_patient', {'id': questionnaire.conseil.id}) }}" class="btn btn-btnback">{{ 'btnRetour' | trans}}</a>
    {% endif %}

{{ form_end(form) }}

templates/certificat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Certificat{% endblock %}

{% block body %}
    <h1>Edit Certificat</h1>

    {{ include('certificat/_form.html.twig', {'button_label': 'btnMettreAjour'|trans, 'btn_c': 'btnupdate'}) }}

    {# <a href="{{ path('app_certificat_index') }}">back to list</a> #}

    {# {{ include('certificat/_delete_form.html.twig') }} #}
{% endblock %}

templates/certificat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Certificat index{% endblock %}

{% block body %}
    <h1>Certificat index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Avis_traitant</th>
                <th>Decision</th>
                <th>Plainte_doleance</th>
                <th>Examen_clinique</th>
                <th>Avis_medecin_conseil</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for certificat in certificats %}
            <tr>
                <td>{{ certificat.id }}</td>
                <td>{{ certificat.avisTraitant }}</td>
                <td>{{ certificat.decision }}</td>
                <td>{{ certificat.plainteDoleance }}</td>
                <td>{{ certificat.examenClinique }}</td>
                <td>{{ certificat.avisMedecinConseil }}</td>
                <td>
                    <a href="{{ path('app_certificat_show', {'id': certificat.id}) }}">show</a>
                    <a href="{{ path('app_certificat_edit', {'id': certificat.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_certificat_new') }}">Create new</a>
{% endblock %}

templates/certificat/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Certificat{% endblock %}

{% block body %}
    <h1>Create new Certificat</h1>

    {{ include('certificat/_form.html.twig', {'button_label': 'btnEnregistrer'|trans, 'btn_c': 'btnsave'}) }}

    {# <a href="{{ path('app_certificat_index') }}">back to list</a> #}
{% endblock %}

templates/certificat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Certificat{% endblock %}

{% block body %}
    <h1>Certificat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ certificat.id }}</td>
            </tr>
            <tr>
                <th>Avis_traitant</th>
                <td>{{ certificat.avisTraitant }}</td>
            </tr>
            <tr>
                <th>Decision</th>
                <td>{{ certificat.decision }}</td>
            </tr>
            <tr>
                <th>Plainte_doleance</th>
                <td>{{ certificat.plainteDoleance }}</td>
            </tr>
            <tr>
                <th>Examen_clinique</th>
                <td>{{ certificat.examenClinique }}</td>
            </tr>
            <tr>
                <th>Avis_medecin_conseil</th>
                <td>{{ certificat.avisMedecinConseil }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_certificat_index') }}">back to list</a>

    <a href="{{ path('app_certificat_edit', {'id': certificat.id}) }}">edit</a>

    {{ include('certificat/_delete_form.html.twig') }}
{% endblock %}