src/Entity/Questionnaire.php
<?php

namespace App\Entity;

use App\Repository\QuestionnaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuestionnaireRepository::class)
 */
class Questionnaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $q1;

    /**
     * @ORM\ManyToMany(targetEntity=Demande::class, inversedBy="questionnaires")
     */
    private $q2;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $q2autre;

    /**
     * @ORM\Column(type="boolean")
     */
    private $q3;

    /**
     * @ORM\Column(type="boolean")
     */
    private $q4;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $q4datesuspension;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $q3datecessation;

    /**
     * @ORM\Column(type="text")
     */
    private $q5;

    /**
     * @ORM\Column(type="text")
     */
    private $q6;

    /**
     * @ORM\Column(type="text")
     */
    private $q7;

    /**
     * @ORM\ManyToOne(targetEntity=Souhait::class, inversedBy="questionnaires")
     */
    private $q8;

    /**
     * @ORM\ManyToOne(targetEntity=Patient::class, inversedBy="questionnaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $patient;

    /**
     * @ORM\OneToOne(targetEntity=Certificat::class, cascade={"persist", "remove"})
     */
    private $certificat;

    /**
     * @ORM\ManyToOne(targetEntity=Conseil::class, inversedBy="questionnaire")
     */
    private $conseil;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $demande_traduction;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_conseil;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $decision_conseil;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numero_certificat;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_transmission_resultat;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numero_bordereau;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lieu_de_rapprochement;

    public function __construct()
    {
        $this->q2 = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isQ1(): ?bool
    {
        return $this->q1;
    }

    public function setQ1(bool $q1): self
    {
        $this->q1 = $q1;

        return $this;
    }

    /**
     * @return Collection<int, Demande>
     */
    public function getQ2(): Collection
    {
        return $this->q2;
    }

    public function addQ2(Demande $q2): self
    {
        if (!$this->q2->contains($q2)) {
            $this->q2[] = $q2;
        }

        return $this;
    }

    public function removeQ2(Demande $q2): self
    {
        $this->q2->removeElement($q2);

        return $this;
    }

    public function getQ2autre(): ?string
    {
        return $this->q2autre;
    }

    public function setQ2autre(?string $q2autre): self
    {
        $this->q2autre = $q2autre;

        return $this;
    }

    public function isQ3(): ?bool
    {
        return $this->q3;
    }

    public function setQ3(bool $q3): self
    {
        $this->q3 = $q3;

        return $this;
    }

    public function isQ4(): ?bool
    {
        return $this->q4;
    }

    public function setQ4(bool $q4): self
    {
        $this->q4 = $q4;

        return $this;
    }

    public function getQ4datesuspension(): ?\DateTimeInterface
    {
        return $this->q4datesuspension;
    }

    public function setQ4datesuspension(?\DateTimeInterface $q4datesuspension): self
    {
        $this->q4datesuspension = $q4datesuspension;

        return $this;
    }

    public function getQ3datecessation(): ?\DateTimeInterface
    {
        return $this->q3datecessation;
    }

    public function setQ3datecessation(?\DateTimeInterface $q3datecessation): self
    {
        $this->q3datecessation = $q3datecessation;

        return $this;
    }

    public function getQ5(): ?string
    {
        return $this->q5;
    }

    public function setQ5(string $q5): self
    {
        $this->q5 = $q5;

        return $this;
    }

    public function getQ6(): ?string
    {
        return $this->q6;
    }

    public function setQ6(string $q6): self
    {
        $this->q6 = $q6;

        return $this;
    }

    public function getQ7(): ?string
    {
        return $this->q7;
    }

    public function setQ7(string $q7): self
    {
        $this->q7 = $q7;

        return $this;
    }

    public function getQ8(): ?Souhait
    {
        return $this->q8;
    }

    public function setQ8(?Souhait $q8): self
    {
        $this->q8 = $q8;

        return $this;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): self
    {
        $this->patient = $patient;

        return $this;
    }

    public function getCertificat(): ?Certificat
    {
        return $this->certificat;
    }

    public function setCertificat(?Certificat $certificat): self
    {
        $this->certificat = $certificat;

        return $this;
    }

    public function getConseil(): ?Conseil
    {
        return $this->conseil;
    }

    public function setConseil(?Conseil $conseil): self
    {
        $this->conseil = $conseil;

        return $this;
    }

    public function getDemandeTraduction(): ?string
    {
        return $this->demande_traduction;
    }

    public function setDemandeTraduction(string $demande_traduction): self
    {
        $this->demande_traduction = $demande_traduction;

        return $this;
    }

    public function getDateConseil(): ?\DateTimeInterface
    {
        return $this->date_conseil;
    }

    public function setDateConseil(?\DateTimeInterface $date_conseil): self
    {
        $this->date_conseil = $date_conseil;

        return $this;
    }

    public function getDecisionConseil(): ?string
    {
        return $this->decision_conseil;
    }

    public function setDecisionConseil(?string $decision_conseil): self
    {
        $this->decision_conseil = $decision_conseil;

        return $this;
    }

    public function getNumeroCertificat(): ?string
    {
        return $this->numero_certificat;
    }

    public function setNumeroCertificat(?string $numero_certificat): self
    {
        $this->numero_certificat = $numero_certificat;

        return $this;
    }

    public function getDateTransmissionResultat(): ?\DateTimeInterface
    {
        return $this->date_transmission_resultat;
    }

    public function setDateTransmissionResultat(?\DateTimeInterface $date_transmission_resultat): self
    {
        $this->date_transmission_resultat = $date_transmission_resultat;

        return $this;
    }

    public function getNumeroBordereau(): ?string
    {
        return $this->numero_bordereau;
    }

    public function setNumeroBordereau(?string $numero_bordereau): self
    {
        $this->numero_bordereau = $numero_bordereau;

        return $this;
    }

    public function getLieuDeRapprochement(): ?string
    {
        return $this->lieu_de_rapprochement;
    }

    public function setLieuDeRapprochement(?string $lieu_de_rapprochement): self
    {
        $this->lieu_de_rapprochement = $lieu_de_rapprochement;

        return $this;
    }
}

src/Controller/QuestionnaireController.php
<?php

namespace App\Controller;

use Fpdf\Fpdf;
use App\Entity\Conseil;
use App\Entity\Evasan;
use App\Entity\Patient;
use App\Entity\Questionnaire;
use App\Form\QuestionnaireType;
use App\Repository\DemandeRepository;
use App\Repository\EvasanRepository;
use App\Repository\QuestionnaireRepository;
use App\Service\QuestionnaireService;
use App\Service\UserService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\Console\Question\Question;

/**
 * @Route("/questionnaire")
 */
class QuestionnaireController extends AbstractController
{
    public $questionnaireService;
    public $userService;
    public function __construct(QuestionnaireService $questionnaireService, UserService $userService)
    {
        $this->questionnaireService = $questionnaireService;
        $this->userService = $userService;
    }
    /**
     * @IsGranted("ROLE_USER")
     * @Route("/", name="app_questionnaire_index", methods={"GET"})
     */
    public function index(QuestionnaireRepository $questionnaireRepository): Response
    {
        return $this->render('questionnaire/index.html.twig', [
            'questionnaires' => $questionnaireRepository->findAll(),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/new/{id}", name="app_questionnaire_new", methods={"GET", "POST"})
     */
    public function new(Request $request, QuestionnaireRepository $questionnaireRepository, Patient $patient): Response
    {
        //dd($patient);
        $questionnaire = new Questionnaire();
        $form = $this->createForm(QuestionnaireType::class, $questionnaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $questionnaire->setPatient($patient);
            //dd($request);
            $questionnaireRepository->add($questionnaire, true);

            return $this->redirectToRoute('app_patient_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('questionnaire/new.html.twig', [
            'questionnaire' => $questionnaire,
            'form' => $form,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/{id}", name="app_questionnaire_show", methods={"GET"})
     */
    public function show(Questionnaire $questionnaire): Response
    {
        return $this->render('questionnaire/show.html.twig', [
            'questionnaire' => $questionnaire,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/{id}/edit", name="app_questionnaire_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Questionnaire $questionnaire, QuestionnaireRepository $questionnaireRepository, DemandeRepository $demandeRepository, EvasanRepository $evasanRepository): Response
    {
        $form = $this->createForm(QuestionnaireType::class, $questionnaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if ($request->request->get('questionnaire')['q1'] == 0) {
                if (isset($request->request->get('questionnaire')['q2'])) {
                    for ($i=0; $i < count($request->request->get('questionnaire')['q2']); $i++) { 
                    $questionnaire->removeQ2($demandeRepository->find($request->request->get('questionnaire')['q2'][$i]));
                }
                }
                
            }
            if ($request->request->get('questionnaire')['q3'] == 1) {
                $questionnaire->setQ3datecessation(null);
            }
            if ($request->request->get('questionnaire')['q4'] == 1) {
                $questionnaire->setQ4datesuspension(null);
            }
            $questionnaireRepository->add($questionnaire, true);
            if ($request->request->get('questionnaire')['q8'] == 5) {
                if(!$evasanRepository->findByQuestionnaire($questionnaire->getId())){
                    $evasan = new Evasan();
                    $evasan->setQuestionnaire($questionnaire);
                    $evasanRepository->add($evasan, true);
                }
            }else{
                if ($evasanRepository->findByQuestionnaire($questionnaire->getId())) {
                    $evasanRepository->remove($evasanRepository->findByQuestionnaire($questionnaire->getId()), true);
                }
            }

            return $this->redirectToRoute('app_questionnaire_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('questionnaire/edit.html.twig', [
            'questionnaire' => $questionnaire,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}/edit/{idC}/conseil/{idP}/patient", name="app_edit_questionnaire")
     * @ParamConverter("conseil", options={"mapping": {"idC" : "id"}})
     * @ParamConverter("patient", options={"mapping": {"idP" : "id"}})
     */
    public function editQuestionnaire(Request $request, Questionnaire $questionnaire, QuestionnaireRepository $questionnaireRepository, DemandeRepository $demandeRepository, EvasanRepository $evasanRepository, Conseil $conseil, Patient $patient): Response
    {
        //dd($request->request);
        //dd($questionnaireRepository->otherQuestion($conseil, $patient));
        $form = $this->createForm(QuestionnaireType::class, $questionnaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            if ($request->request->get('questionnaire')['q1'] == 0) {
                if (isset($request->request->get('questionnaire')['q2'])) {
                    for ($i=0; $i < count($request->request->get('questionnaire')['q2']); $i++) { 
                    $questionnaire->removeQ2($demandeRepository->find($request->request->get('questionnaire')['q2'][$i]));
                }
                }
                
            }
            if ($request->request->get('questionnaire')['q3'] == 1) {
                $questionnaire->setQ3datecessation(null);
            }
            if ($request->request->get('questionnaire')['q4'] == 1) {
                $questionnaire->setQ4datesuspension(null);
            }
            $questionnaireRepository->add($questionnaire, true);
            if ($request->request->get('questionnaire')['q8'] == 5) {
                if(!$evasanRepository->findByQuestionnaire($questionnaire->getId())){
                    $evasan = new Evasan();
                    $evasan->setQuestionnaire($questionnaire);
                    $evasanRepository->add($evasan, true);
                }
            }else{
                if ($evasanRepository->findByQuestionnaire($questionnaire->getId())) {
                    $evasanRepository->remove($evasanRepository->findByQuestionnaire($questionnaire->getId()), true);
                }
            }
            return $this->redirectToRoute('coneil_patient', ['id'=>$conseil->getId()]);
            //return $this->redirectToRoute('app_questionnaire_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('questionnaire/edit.html.twig', [
            'questionnaire' => $questionnaire,
            'questionnaires' => $questionnaireRepository->otherQuestion($conseil, $patient),
            'form' => $form,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/{id}", name="app_questionnaire_delete", methods={"POST"})
     */
    public function delete(Request $request, Questionnaire $questionnaire, QuestionnaireRepository $questionnaireRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$questionnaire->getId(), $request->request->get('_token'))) {
            $questionnaireRepository->remove($questionnaire, true);
        }

        return $this->redirectToRoute('app_questionnaire_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/delete/{id}", name="app_delete_questionnaire")
     */
    public function deleteQuestionnaire(Request $request, Questionnaire $questionnaire, QuestionnaireRepository $questionnaireRepository): Response
    {
        if ($questionnaire) {
            $conseil = $questionnaire->getConseil();
            $questionnaireRepository->remove($questionnaire, true);
            return $this->redirectToRoute('coneil_patient', ['id'=>$conseil->getId()]);
        }
        return $this->redirectToRoute('app_conseil_index');
        
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/conseil/patient/{idC}/{idP}", name="app_questionnaire_conseil_patient_new", methods={"GET", "POST"})
     * @ParamConverter("conseil", options={"mapping": {"idC" : "id"}})
     * @ParamConverter("patient", options={"mapping": {"idP" : "id"}})
     */
    public function newConseilPatient(Request $request, Conseil $conseil, Patient $patient, QuestionnaireRepository $questionnaireRepository, EvasanRepository $evasanRepository): Response
    {
        //dd($questionnaireRepository->otherQuestion($request->query->get('idC'), $request->query->get('idP')));
        $questionnaire = new Questionnaire();
        $form = $this->createForm(QuestionnaireType::class, $questionnaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $questionnaire->setPatient($patient);
            $questionnaire->setConseil($conseil);
            $questionnaireRepository->add($questionnaire, true);
            if ($request->request->get('questionnaire')['q8'] == 5) {
                if(!$evasanRepository->findByQuestionnaire($questionnaire->getId())){
                    $evasan = new Evasan();
                    $evasan->setQuestionnaire($questionnaire);
                    $evasanRepository->add($evasan, true);

templates/questionnaire/_delete_form.html.twig
<form method="post" action="{{ path('app_questionnaire_delete', {'id': questionnaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ questionnaire.id) }}">
    <button class="btn">Delete</button>
</form>

templates/questionnaire/_form.html.twig
{{ form_start(form, {'attr': {'id': 'questionnaire'}}) }}
    <div class="row">
        <div>{{ form_row(form.q1, {'label': 'q1'|trans}) }}</div>
    </div>
    <div class="row" id="q2">
        <div>
            {{ form_row(form.q2, {'label': 'q2'|trans})}}
        </div> 
    </div>
    <div class="row" id="r_questionnaire_q2autre">
        <div>
            {{ form_row(form.q2autre, {'label': 'q2autre'|trans})}}
        </div> 
    </div>
    <div class="row">
        <div>
            {{ form_row(form.q3, {'label': 'q3'|trans})}}
        </div> 
    </div>
    <div class="row" id="datecessation">
        <div>
            {{ form_row(form.q3datecessation, {'label': 'q3datecessation'|trans})}}
        </div> 
    </div>
    
    <div class="row">
        <div>
            {{ form_row(form.q4, {'label': 'q4'|trans})}}
        </div> 
    </div>
    <div class="row" id="datesuspension">
        <div>
            {{ form_row(form.q4datesuspension, {'label': 'q4datesuspension'|trans})}}
        </div> 
    </div>
    <div class="row">
        <div>
            {{ form_row(form.q5, {'label': 'q5'|trans})}}
        </div> 
    </div>
    <div class="row">
        <div>
            {{ form_row(form.q6, {'label': 'q6'|trans})}}
        </div> 
    </div>
    <div class="row">
        <div>
            {{ form_row(form.q7, {'label': 'q7'|trans})}}
        </div> 
    </div>
    <div class="row">
        <div>
            {{ form_row(form.q8, {'label': 'q8'|trans})}}
        </div> 
            {{ form_row(form.lieu_de_rapprochement) }}
    </div>
    {{ form_row(form.demande_traduction) }}
    <fieldset>INFORMATION SUPPLEMENTAIRE</fieldset>
    {{ form_rest(form) }}
    <button class="btn btn-btnsave">{{ button_label|default('Save') }}</button>
    <a href="{{ path('coneil_patient', {'id': id}) }}" class="btn btn-btnback">{{'btnRetour'|trans}}</a>
    {% if app.request.attributes.get('_route') == 'app_edit_questionnaire' %}
        <a href="{{ path('app_delete_questionnaire', {'id': idQ}) }}" class="btn btn-btndelete">{{ 'btnSupprimer'| trans }} </a>
    {% endif %}
{{ form_end(form) }}

templates/questionnaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Questionnaire{% endblock %}

{% block body %}
    <div class="container">
        <h1>{{ 'questionnaire'| trans }}</h1>

        {% if questionnaires | length > 0 %}
            <table>
            <thead>
                <tr>
                    <td>Objet</td>
                    <td>Decision</td>
                    <td>Date Consil</td>
                </tr>
            </thead>
            <tboddy>
                {% for q in questionnaires %}
                    <tr>
                        <td>{{q.q8.nom}}</td>
                        {# <td>
                        {% for demande in q.q2 %}
                            <div>{{demande.nom}}</div>
                        {% endfor %}
                        </td> #}
                        <td>{{q.decisionConseil}}</td>
                        <td>{{q.conseil.nom}}</td>
                    </tr>
                {% endfor %}
            </tboddy>
        </table>
        {% endif %}
        
        

        {{ include('questionnaire/_form.html.twig', {'button_label': 'btnMettreAjour'|trans , 'id': questionnaire.conseil.id, 'idQ': questionnaire.id}) }}

        {# <a href="{{ path('app_questionnaire_index') }}">back to list</a> #}

        {# {{ include('questionnaire/_delete_form.html.twig') }} #}

    </div>
{% endblock %}

templates/questionnaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Questionnaire index{% endblock %}

{% block body %}
    <h1>Questionnaire index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Q1</th>
                <th>Q2autre</th>
                <th>Q3</th>
                <th>Q4</th>
                <th>Q4datesuspension</th>
                <th>Q3datecessation</th>
                <th>Q5</th>
                <th>Q6</th>
                <th>Q7</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for questionnaire in questionnaires %}
            <tr>
                <td>{{ questionnaire.id }}</td>
                <td>{{ questionnaire.q1 ? 'Yes' : 'No' }}</td>
                <td>{{ questionnaire.q2autre }}</td>
                <td>{{ questionnaire.q3 ? 'Yes' : 'No' }}</td>
                <td>{{ questionnaire.q4 ? 'Yes' : 'No' }}</td>
                <td>{{ questionnaire.q4datesuspension ? questionnaire.q4datesuspension|date('Y-m-d') : '' }}</td>
                <td>{{ questionnaire.q3datecessation ? questionnaire.q3datecessation|date('Y-m-d') : '' }}</td>
                <td>{{ questionnaire.q5 }}</td>
                <td>{{ questionnaire.q6 }}</td>
                <td>{{ questionnaire.q7 }}</td>
                <td>
                    <a href="{{ path('app_questionnaire_show', {'id': questionnaire.id}) }}">show</a>
                    <a href="{{ path('app_questionnaire_edit', {'id': questionnaire.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('app_questionnaire_new') }}">Create new</a> #}
{% endblock %}

templates/questionnaire/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Questionnaire{% endblock %}

{% block body %}
    <div class="container">
        <h1>{{ 'questionnaire' | trans }}</h1>
        {% if questionnaires | length > 0 %}
            <table>
                <thead>
                    <tr>
                        <td>Objet</td>
                        <td>Decision</td>
                        <td>Date Consil</td>
                    </tr>
                </thead>
                <tboddy>
                    {% for q in questionnaires %}
                        <tr>
                            <td>{{q.q8.nom}}</td>
                            {# <td>
                            {% for demande in q.q2 %}
                                <div>{{demande.nom}}</div>
                            {% endfor %}
                            </td> #}
                            <td>{{q.decisionConseil}}</td>
                            <td>{{q.conseil.nom}}</td>
                        </tr>
                    {% endfor %}
                </tboddy>
            </table>
        {% endif %}

        {{ include('questionnaire/_form.html.twig', {'button_label': 'btnEnregistrer'|trans , 'id': conseil.id}) }}

        {# <a href="{{ path('app_questionnaire_index') }}">back to list</a> #}
    </div>
    
{% endblock %}

templates/questionnaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Questionnaire{% endblock %}

{% block body %}
    <h1>Questionnaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ questionnaire.id }}</td>
            </tr>
            <tr>
                <th>Q1</th>
                <td>{{ questionnaire.q1 ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Q2autre</th>
                <td>{{ questionnaire.q2autre }}</td>
            </tr>
            <tr>
                <th>Q3</th>
                <td>{{ questionnaire.q3 ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Q2anneecessation</th>
                <td>{{ questionnaire.q2anneecessation }}</td>
            </tr>
            <tr>
                <th>Q4</th>
                <td>{{ questionnaire.q4 ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Q4datesuspension</th>
                <td>{{ questionnaire.q4datesuspension ? questionnaire.q4datesuspension|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Q3datecessation</th>
                <td>{{ questionnaire.q3datecessation ? questionnaire.q3datecessation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Q5</th>
                <td>{{ questionnaire.q5 }}</td>
            </tr>
            <tr>
                <th>Q6</th>
                <td>{{ questionnaire.q6 }}</td>
            </tr>
            <tr>
                <th>Q7</th>
                <td>{{ questionnaire.q7 }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_questionnaire_index') }}">back to list</a>

    <a href="{{ path('app_questionnaire_edit', {'id': questionnaire.id}) }}">edit</a>

    {{ include('questionnaire/_delete_form.html.twig') }}
{% endblock %}

templates/questionnaire/testa.html.twig
{% if getQuestionnaire(4,6) %}
    <div>OK</div>
{% else %}
    <div>KO</div>
{% endif %}